### PR TITLE
Issue 3

### PR DESCRIPTION
**Pull request by ParthBarot-BoTreeConsulting**
User Nike+ activities method should allow to pass count of records to be fetched from Nike+ server using Nike+ API.

Update files,
- person.rb
- activities.rb

### CODE REVIEW

**Comment by fuelxc** [comment]
I actually made an update last night that i haven't pushed as I need to fix a couple tests i broke that allows you to pass options (not just count).  Could you you remove this commit from your pulls, I will merge the others today and push a new gem. (0.2.0)

It slightly changes how we build things,  Do you use the caching of the the activities?   I removed it as the api allows for (though not working right now) searching by dates.

**Comment by ParthBarot-BoTreeConsulting** [comment]
Hi,

Sure, I will remove the "count option passing" implementation. 

As of now, i follow these steps to access all activities,
1. Create person
2. Call `p.activities(100).fetch_all`
3. Access all activities using `p.activities`

Please let me know when you fix this, till than i will be using forked version of your repo.

PS: All pull request i submitted are incremental in order, means the later ones containing all code from prior branches. Please let me know if anything else needed on this.

Thanks,
Parth Barot.

**Comment by fuelxc** [comment]
The way I updated it you would use :count => 100.

I will push new gem today.

Cheers

**Comment by ParthBarot-BoTreeConsulting** [comment]
Thanks, i will then use the latest version. Btw, I am wondering how i can fetch all latest code from your repo to mine.

**Comment by ParthBarot-BoTreeConsulting** [comment]
Other than this, i have also tried to generate POST request for access token generation using `mechanize`. It responds with status 200, but access token is not returned. I was wondering, If we could get that as well using ruby code.

**Comment by fuelxc** [comment]
The api seems buggy or incomplete at this time.  Offset was broken when I first implemented the fetch_more and I noticed the date range is broken too right now.

I tried to mimic their js implementation as well and I wasn't getting a token back either.  They have some magic it seems with the auth token request.

**Comment by fuelxc** [comment]
already updated the fetch to accept parameters.

**Comment by fuelxc** [comment]
Here is a little tutorial on fetching code upstream (my repo)

http://robots.thoughtbot.com/post/5133345960/keeping-a-github-fork-updated

I will need you to rebase and resend the pull request for the other changes

**Comment by ParthBarot-BoTreeConsulting** [comment]
For that, i guess i need to merge `issue_3` into `issue_7` branch. Would that help merging all the changes?

**Comment by fuelxc** [comment]
looking at the pull request for 7, it looks like the commit for 3 is already in there.

We just need to remove the changes for the count really.  If you can't remove the commit I can manually merge it.

**Comment by ParthBarot-BoTreeConsulting** [comment]
I have removed those from `issue_7`, please check and merge it.

**Comment by fuelxc** [comment]
all merged in, i want to make some more tests up for your stuff before I release a new gem.

**Comment by ParthBarot-BoTreeConsulting** [comment]
Thanks, awaiting the new version :). I will merge latest code into my repo as well, to avoid any future confusions.

**Pull request closed without merging**
